---
include:
  - https://gitlab.exphost.pl/exphost/exphost-helms/-/raw/master/common/gitlab-ci.yml

stages:
- deploy
- test
- cleanup
- upload


upload:
  extends: .upload
  only:
    - tags
    - master

deploy:
  stage: deploy
  image:
    name: alpine/helm
  environment: 
    name: dev/$CI_COMMIT_REF_SLUG
    on_stop: delete_app
  script:
  - export VERSION=$(git describe --tags)
  - sed -i "s/__VERSION__/$VERSION/" chart/Chart.yaml
  - echo "CI_ENVIRONMENT_SLUG $CI_ENVIRONMENT_SLUG"
  - echo "CI_ENVIRONMENT_SLUG $CI_ENVIRONMENT_SLUG"
  - echo "KUBE_NAMESPACE $KUBE_NAMESPACE"
  - >
    helm upgrade -n $KUBE_NAMESPACE -i test-openldap chart -f gitlab-ci-values.yml
    --set podAnnotations."app\.gitlab\.com/app"=$CI_PROJECT_PATH_SLUG
    --set podAnnotations."app\.gitlab\.com/env"=$CI_ENVIRONMENT_SLUG
    --wait --wait-for-jobs
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_BRANCH

delete_app:
  stage: cleanup
  image:
    name: alpine/helm
  script:
    - helm uninstall -n $KUBE_NAMESPACE test-openldap --wait
  variables:
    GIT_STRATEGY: none
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    action: stop
  needs:
    - deploy
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_BRANCH

test:
  stage: test
  image:
    name: alpine/helm
  environment: 
    name: dev/$CI_COMMIT_REF_SLUG
    on_stop: delete_app
  variables:
    GIT_STRATEGY: none
  script:
    - helm test -n $KUBE_NAMESPACE test-openldap --logs
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_BRANCH
