adminPassword:
  password: pass123
configAdminPassword:
  password: passpass123
initialDB:
  serviceaccounts:
  - name: dex
    password: dex123
  - name: postfix
    password: postfix123
#podAnnotations:
#  app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
#  app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
