{{- if not (.Values.adminPassword.password | default .Values.adminPassword.existingSecret | default false) }}
---
apiVersion: exphost.pl/v1
kind: Password
metadata:
  name: {{ include "chart.fullname" . }}-admin
spec:
  name: {{ include "chart.fullname" . }}-admin
  copy_namespaces: {{ .Values.adminPassword.generateToNamespaces }}
{{ end }}

{{- if not (.Values.configAdminPassword.password | default .Values.configAdminPassword.existingSecret | default false) }}
---
apiVersion: exphost.pl/v1
kind: Password
metadata:
  name: {{ include "chart.fullname" . }}-configadmin
spec:
  name: {{ include "chart.fullname" . }}-configadmin
  copy_namespaces: {{ .Values.configAdminPassword.generateToNamespaces }}
{{ end }}
