apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-postfixuser-ldap-schema
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: ldap
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command:
          - /bin/bash
          - -ce
          - 'echo -e "$LDIF" >/tmp/ldif.ldif;
            cat /tmp/ldif.ldif;
            ldapmodify -a -x -H ldap://{{ include "chart.fullname" $ }} -D cn=admin,cn=config -w "$ADMINPASSWORD" -f /tmp/ldif.ldif;
            R=$?
            echo $R
            exit $R
            '
        env:
          - name: LDIF
            value: |
              dn: cn=postfix,cn=schema,cn=config
              changetype: add
              cn: postfix
              objectclass: olcSchemaConfig
              olcattributetypes: {0}(1.3.6.1.4.1.4203.666.1.200 NAME 'mailacceptinggeneralid' DESC 'Postfix mail local address alias attribute' EQUALITY caseIgnoreMatch SUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{1024})
              olcattributetypes: {1}(1.3.6.1.4.1.4203.666.1.201 NAME 'maildrop' DESC 'Postfix mail final destination attribute' EQUALITY caseIgnoreMatch SUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{1024})
              olcobjectclasses: {0}(1.3.6.1.4.1.4203.666.1.100 NAME 'postfixUser' DESC 'Postfix mail user class' SUP top AUXILIARY MAY(mailacceptinggeneralid $ maildrop))
          - name: ADMINPASSWORD
{{- if .Values.configAdminPassword.password }}
            value: "{{ .Values.configAdminPassword.password }}"
{{- else }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.configAdminPassword.existingSecret | default (print "password-" (include "chart.fullname" .) "-configadmin-from-" .Release.Namespace) }}
                key: {{ .Values.configAdminPassword.existingSecretKey }}
{{- end }}
