{{- range .Values.initialDB.serviceaccounts }}
{{   if not (.password | default .existingSecret | default false) }}
---
apiVersion: exphost.pl/v1
kind: Password
metadata:
  name: {{ include "chart.fullname" $ }}-sa-{{ .name }}
spec:
  name: {{ include "chart.fullname" $ }}-sa-{{ .name }}
#  types:
#    - sha512
{{- if .copyNamespaces }}
  copy_namespaces: {{ .copyNamespaces | toYaml | nindent 4 }}
{{- end }}
{{   end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" $ }}-create-sa-{{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: ldap
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: "{{ $.Values.image.pullPolicy }}"
        command:
          - /bin/bash
          - -c
          - 'set -x; echo "AA_${PASSWORD}_BB"; echo "CC_${ADMINPASSWORD}_DD"; 
PASSWORD_HASH=$(echo $PASSWORD|openssl passwd -6 -stdin);
echo "EE_${PASSWORD_HASH}_FF";
echo -e "
dn: uid={{ .name }},ou=sa,{{ include "ldap.dc" $ }}\n
changetype: add\n
uid: {{ .name }}\n
objectClass: account\n
objectClass: simpleSecurityObject\n
userPassword:: $(echo -n {crypt}${PASSWORD_HASH}|base64 -w0)\n
"|sed -e "s/^ //" >/tmp/ldif.ldif
            ;
            cat /tmp/ldif.ldif;
            ldapmodify -d2 -a -x -H ldap://{{ include "chart.fullname" $ }} -D cn=admin,{{ include "ldap.dc" $ }} -w "$ADMINPASSWORD" -f /tmp/ldif.ldif;
            ret=$?;
            echo $ret;
            exit $ret;
            '
        env:
          - name: PASSWORD
{{- if .password }}
            value: "{{ .password }}"
{{- else }}
            valueFrom:
              secretKeyRef:
                name: {{ .existingSecret | default (print "password-" (include "chart.fullname" $) "-sa-" .name "-from-" $.Release.Namespace) }}
                key: {{ .existingSecretKey | default "password"}}
{{- end }}
          - name: ADMINPASSWORD
{{- if $.Values.adminPassword.password }}
            value: "{{ $.Values.adminPassword.password }}"
{{- else }}
            valueFrom:
              secretKeyRef:
                name: {{ $.Values.adminPassword.existingSecret | default (print "password-" (include "chart.fullname" $) "-admin-from-" $.Release.Namespace) }}
                key: {{ $.Values.adminPassword.existingSecretKey }}
{{- end }}
{{ end }}

