apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp-ldap
      protocol: TCP
      name: tcp-ldap
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
